name: churn-prod-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - scikit-learn=1.3.0
  - pandas=1.5.3
  - pip
  - pip:
    - azureml-mlflow==1.49.0
    - fsspec
    - adlfs
    - azureml-fsspec