$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: >-
  python train.py
  --data_path ${{inputs.training_data}}
code: .
inputs:
  training_data:
    type: uri_file
    path: azureml:churn-training-data:1 # Use the name and version of your data asset
environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
  conda_file: ./environment.yml
compute: azureml:cpu-cluster-1 # Use the name of your compute cluster
display_name: churn-training-job
experiment_name: churn-prediction-training
