$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: >-
  python train.py
  --data_path ${{inputs.training_data}}
code: .
inputs:
  training_data:
    type: uri_file
    path: azureml://subscriptions/ac58d39e-10ad-40b4-b10e-ce9dbb1efc8d/resourcegroups/Cloud_4_10/workspaces/Cloud_assignment/datastores/workspaceblobstore/paths/UI/2025-10-04_072843_UTC/
    mode: direct
environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
  conda_file: ./environment.yml
compute: azureml:cpu-cluster-1
display_name: churn-training-job
experiment_name: churn-prediction-training